### PR TITLE
chore: ci and publish actions

### PR DESCRIPTION
**Pull request by westeezy**
setting up CI for running tests on `main` and new PRs.
also adding publish action, which won't work until I set up tokens, but we will eventually need it.

### CODE REVIEW

**Comment by RatnadeepSimhadri** [comment]
@westeezy , The Release would it be possible to parameterize the version ? as given here 
https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like

**Review by RatnadeepSimhadri — APPROVED** [review]
Looks Good. Thanks @westeezy for the PR , Only Question is can we parameterize the Release Version like 
https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like

**Comment by westeezy** [comment]
we are currently leveraging semantic commits for versioning in other repos but i think

> Looks Good. Thanks @westeezy for the PR , Only Question is can we parameterize the Release Version like https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like

We are currently using conventional commits to derive versions eg `feat:` is a minor, `bug:` is a patch, and `!`'ed messages are breaking changes. That being said you don't have to follow that rule like we do, but if you choose to not leverage conventional commits there are some packages you can remove. Let's keep this PR with the intent of using conventional commits and you can remove them and version how you like in the future.

**Comment by RatnadeepSimhadri** [comment]
> we are currently leveraging semantic commits for versioning in other repos but i think
> 
> > Looks Good. Thanks @westeezy for the PR , Only Question is can we parameterize the Release Version like https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like
> 
> We are currently using conventional commits to derive versions eg `feat:` is a minor, `bug:` is a patch, and `!`'ed messages are breaking/major changes. That being said you don't have to follow that rule like we do, but if you choose to not leverage conventional commits there are some packages you can remove. Let's keep this PR with the intent of using conventional commits and you can remove them and version how you like in the future.

Thanks 👍

**Pull request merged**
